services:
  - type: web
    name: roblox-script-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
